[build]
  base = "Code/frontend"
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"